name: Configuration Check
on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Deployment Environment'
        default: 'dev'
        # type: choice
        # required: true
        # options:
        #   - dev
        #   - stage
        #   - prod
jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello

  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Hi
        run: echo hi
      - name: Fail the job
        run: exit 1  # This step will make the job fail
  test2:
    name: Run test2
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
      - name: Sleep for 10 seconds
        run: sleep 30
      - name: Fail the job
        run: exit 1
  test3:
    name: Run test3
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
      - name: Sleep for 10 seconds
        run: sleep 10
  
