name: Configuration test
on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Deployment Environment'
        default: 'dev'
        # type: choice
        # required: true
        # options:
        #   - dev
        #   - stage
        #   - prod
jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
      - name: Run script
        run: bash ./src/script/script.sh
        env:
          secret: ${{ secrets.SLACK_WEBHOOK_URL }}