name: Hello World on PR Comment

on:
  issue_comment:
    types: [created]

permissions: 
  pull-requests: write 
  id-token: write
  issues: write
  contents: read 

jobs:
  display-comment:
    runs-on: ubuntu-latest
    # Only run for comments on pull requests
    # if: github.event.issue.pull_request
    if: ${{ github.event.issue.pull_request && github.actor != 'github-actions[bot]' && startsWith(github.event.comment.body, 'AZ-') }}


    steps:
      - name: Display Comment
        run: |
          echo "Hello World! PR Comment: ${{ github.event.comment.body }}"

      - name: Remove slash and display OS name
        run: |
          os_name=$(echo "${{ github.event.comment.body }}" | sed 's/^AZ-//')
          echo "Processed OS name: $os_name"

      - name: Sleep
        run: sleep 30

      - name: Add simple comment to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN_GH }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Terraform plan completed! Review the plan output above.'
            })

# name: "Deploy on Comment"
# on: 
#   pull_request:
#     types:
#       - opened
#       - synchronize
#     # branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Deploy
#         run: |
#           echo "Deploying..."