name: Hello World on PR Comment

on:
  issue_comment:
    types: [created]

permissions: 
  pull-requests: write 
  id-token: write
  issues: write
  contents: read 

jobs:
  display-comment:
    runs-on: ubuntu-latest
    # Only run for comments on pull requests
    # if: github.event.issue.pull_request
    if: ${{ github.event.issue.pull_request && github.actor != 'github-actions[bot]' && startsWith(github.event.comment.body, 'AZ-') }}


    steps:
      - name: Display Comment
        run: |
          echo "Hello World! PR Comment: ${{ github.event.comment.body }}"

      - name: Set Image name and version a
        run: |
          image_name=$(echo "${{ github.event.comment.body }}" | sed 's/^AZ-//')
          echo "Image name: $image_name"
          echo "IMAGE_NAME=$image_name" >> $GITHUB_ENV
          case "$image_name" in
          AKS)
            image_version="aks-engine-ubuntu-2004-202301"
            USERNAME="azureuser"
            image_publisher="microsoft-aks"
            IMAGE_OFFER="aks"
            ;;
          Ubuntu)
            image_version="22_04-lts-gen2"
            USERNAME="azureuser"
            image_publisher="Canonical"
            IMAGE_OFFER="0001-com-ubuntu-server-jammy"
            ;;
          Debian)
            image_version="12"
            USERNAME="azureuser"
            IMAGE_OFFER="debian-12"
            image_publisher="Debian"
            image_sku="12"
            ;;
          Almalinux)
            image_version="9-gen2"
            USERNAME="azureuser"
            image_publisher="almalinux"
            IMAGE_OFFER="almalinux-x86_64"
            ;;
          *)
            echo "Unsupported OS: $image_name"
            exit 1
            ;;
          esac

          echo "VERSION=$image_version" >> $GITHUB_ENV
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "image_publisher=$image_publisher" >> $GITHUB_ENV
          echo "IMAGE_OFFER=$IMAGE_OFFER" >> $GITHUB_ENV

      - name: Image Name
        run: |
            echo "Image name is = $IMAGE_NAME"
            echo "Image version is = $VERSION"
            echo "image_publisher=$image_publisher"
            echo "IMAGE_OFFER=$IMAGE_OFFER"
        
      - name: Sleep
        run: sleep 30

      - name: Add simple comment to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN_GH }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Terraform plan completed! Review the plan output above.'
            })

# name: "Deploy on Comment"
# on: 
#   pull_request:
#     types:
#       - opened
#       - synchronize
#     # branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Deploy
#         run: |
#           echo "Deploying..."